### ISSUE TITLE
Multiple browser windows in a node

### ISSUE THREAD

**Issue by AJ-72** [aimmac23/selenium-video-node#12]
Hi,
Does the recording work correctly if I have multiple instances of a browser in same node?

**Comment by aimmac23** [comment]
Hi,

You can have multiple browser TYPES in the same node (Firefox, Internet Explorer, Chrome), but the node can only record one running instance at a time.

If multiple instances were allowed, then the result would be that you would have two browsers on the same screen - but one browser window would likely be on top of the other browser window, which isn't very useful.

You can still run multiple nodes on the same machine if the nodes are using separate desktops. This is possible out-of-the-box with Linux (which supports multiple concurrent logons, as well as virtual X servers), and I believe its also possible under Windows if you have RDP sessions (but don't disconnect the RDP connection, because you will get a blank screen otherwise).

I hope that helps,

Alasdair Macmillan

**Comment by aimmac23** [comment]
Old issue (and question answered) - closing.
