### ISSUE TITLE
Compatibility with Selenium 3

### ISSUE THREAD

**Issue by mhardin** [aimmac23/selenium-video-node#24]
Hi,

Selenium 3 will be arriving soon and your plugin is not compatible with it.  Do you know when you'll expect to update the project to be compatible with Selenium 3.0?

**Comment by mhardin** [comment]
I may have this working locally with Selenium 3.0.0-beta3.  Are you going to want to wait for Selenium 3 to officially release?

**Comment by aimmac23** [comment]
Hi Mhardin,

Thanks for pointing out the issue - I think this would need fixing before Selenium 3 comes out, since the Selenium website is now handing out the beta version by default.

After a quick look, I note a compile error around using a static field from RegistrationRequest, but I think it will need a proper re-test tomorrow. And a consultation with the new docs to find out what the registration attribute is now called :)

Thanks,

Alasdair

**Comment by mhardin** [comment]
Hey @aimmac23 ,

I created this pull request for your convenience as I built it locally to work with Selenium 3.  Hope this helps!

-Matthew

https://github.com/aimmac23/selenium-video-node/pull/25

**Comment by aimmac23** [comment]
This got fixed by mhardin - closing issue.
