### ISSUE TITLE
com.aimmac23.hub.servlet.HubVideoDownloadServlet cannot be instantiated

### ISSUE THREAD

**Issue by ricmoreira** [aimmac23/selenium-video-node#31]
Hello,

I'm trying to run your app but I'm getting an error. I'm running on a Ubuntu x64 machine and have compiled the latest version. Any ideas of what it is the cause?
Thank you.

**This is the command:**
```
java -cp /mypath/selenium-video-node-2.1.jar:/mypath/selenium-server-standalone-3.0.1.jar org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.hub.servlet.HubVideoDownloadServlet -role hub
```
**This is the output:**
```
14:28:28.592 INFO - Selenium build info: version: '3.0.1', revision: '1969d75'
14:28:28.592 INFO - Launching Selenium Grid hub
14:28:29.069 WARN - The specified class : com.aimmac23.hub.servlet.HubVideoDownloadServlet cannot be instantiated com.aimmac23.hub.servlet.HubVideoDownloadServlet
2016-12-21 14:28:29.082:INFO::main: Logging initialized @733ms
14:28:29.089 INFO - Will listen on 4444
2016-12-21 14:28:29.120:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2016-12-21 14:28:29.149:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@6a79c292{/,null,AVAILABLE}
2016-12-21 14:28:29.165:INFO:osjs.ServerConnector:main: Started ServerConnector@59717824{HTTP/1.1}{0.0.0.0:4444}
2016-12-21 14:28:29.166:INFO:osjs.Server:main: Started @817ms
14:28:29.170 INFO - Nodes should register to http://192.168.110.37:4444/grid/register/
14:28:29.170 INFO - Selenium Grid hub is up and running
```

**Comment by aimmac23** [comment]
Hi ricmoreira,

That looks a bit odd - I can't see anything obvious in the code that would cause that, and your command line command looks fine.

If you run it again without the "selenium-video-node" JAR file on the classpath, is the error message exactly the same? I don't think Java checks that the classpath elements exist on disk before running, so that could be one cause.

There's one place in the code that could do with a logging line which could be helpful - HubVideoRegistry, where it says "throw new Error(". Since it sounds like you have the code checked out, would you mind adding it and trying again? I'll add it to the repository tomorrow.

Thanks,

Alasdair

**Comment by ricmoreira** [comment]
Hello Alasdair,

The cause was really "mypath". Sorry for the false alarm and thank you for your help.

Ricardo

**Comment by aimmac23** [comment]
Don't worry about it - I've done that a few times myself....

Alasdair
