### ISSUE TITLE
How to start appium node

### ISSUE THREAD

**Issue by shyam27** [aimmac23/selenium-video-node#34]
Hi,Thanks for sharing this amazing plugin.
I tried with web testing video recording and its worked perfectly, same i have to do it for mobile. 

I tried to start my appium node using --nodeconfig json file where i am specifying the proxy class name as "com.aimmac23.hub.proxy.VideoProxy" and servlet name as "com.aimmac23.node.servlet.VideoRecordingControlServlet" and other as well like port,hubport..etc.

I started my hub with below command :
 java -cp selenium-video-node-2.0.jar:selenium-server-standalone-3.0.1.jar org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.hub.servlet.HubVideoDownloadServlet -role hub

And node with below command : 
node "D:\Appium\Appium\node_modules\appium\bin\appium.js" --nodeconfig D:\nodeconfig_device1.json -p 4721 -bp 5000 -U 07cb78fjf89dfd

In the logs i am seeing 

> <-- POST /extra/VideoRecordingControlServlet?command=reset 404 

```
: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
: Appium REST http interface listener started on 0.0.0.0:4721
: [debug] Non-default server args: {"udid":"07cb78fjf89dfd","port":4721,"bootstrapPort":5000,"nodeconfig":"D:\\nodeconfig_device1.json"}
: Console LogLevel: debug
: [debug] starting auto register thread for grid. Will try to register every 5000 ms.
: --> POST /extra/VideoRecordingControlServlet?command=reset {}
: [debug] Responding to client that we did not find a valid resource
: <-- POST /extra/VideoRecordingControlServlet?command=reset 404 8.330 ms - 47
: [debug] Appium successfully registered with the grid on localhost:4444
: --> GET /wd/hub/status {}
: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
: <-- GET /wd/hub/status 200 3.193 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
: --> GET /wd/hub/status {}
```

If a new session requested i will get 404 error for start recording as well. 
Kindly help me to how to start a appium node with custom servlet and proxy.

Thanks inadvance.

**Comment by aimmac23** [comment]
Hi shyam27,

Unfortunately... this project doesn't support mobile devices, or Appium. The reason is that a lot of the project is written in Java and C code (for speed), and the compiled C code isn't very portable.

From some Googling on the internet, some of the Appium developers gave video recording a go, but closed the issue without offering it themselves: https://github.com/appium/appium/issues/4395. It does seem to be rather difficult to write a third-party video recording application, and the Android/iOS screen recorder APIs aren't all that well unified.

Sorry I can't help further on this. It may be worth checking out Saucelabs to see if they have this feature (although their pricing is rather high).

Alasdair

**Comment by shyam27** [comment]
No problem Alasdair and thanks for the info.
