### ISSUE TITLE
Blank when using disconnected RDP connection

### ISSUE THREAD

**Issue by madaniel** [aimmac23/selenium-video-node#37]
I saw your comments on the issue when using Selenium as a Service - but I'm using Selenium with batch files running by Java - and the results are the same.

Can I override the blank issue w/o using VNC ?

**Comment by aimmac23** [comment]
Hi madaniel,

There's no way to change this - its a design decision by Windows not to render anything on the screen when the user cannot possibly see it. Since we rely on Windows to tell us what the web browser has rendered, there's nothing we can do.

If you're testing on Firefox/Chrome and you don't require Windows you could consider moving your testing onto Linux using an Xvfb screen - which covers exactly this use-case :)

Good luck,

Alasdair

**Comment by madaniel** [comment]
OK.
Thanks for you answer.
