### ISSUE TITLE
Question : How to retrieve video.path value into my java code?

### ISSUE THREAD

**Issue by hemanthsridhar** [aimmac23/selenium-video-node#39]
Hi Alistair,

How to get the value of video.path in my java code. I tried, System.getProperty("video.path") but I am getting null.
Thanks for your help in advance.

Regards,
Hemanth Sridhar

**Comment by aimmac23** [comment]
Hi Hemanth,

The "video.path" system property is set on the command line, when the JVM
starts up - you need to set it yourself with -Dvideo.path=<path>. Make sure
you put it before the name of the main method class ("GridLauncherV3"),
otherwise Java assumes its a command line argument.

Thanks,

Alasdair

On 4 Apr 2017 17:47, "Hemanth Sridhar" <notifications@github.com> wrote:

Hi Alistair,

How to get the value of video.path in my java code. I tried,
System.getProperty("video.path") but I am getting null.
Thanks for your help in advance.

Regards,
Hemanth Sridhar

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aimmac23/selenium-video-node/issues/39>, or mute the
thread

**Comment by hemanthsridhar** [comment]
java -cp selenium-video-node-2.0.jar;selenium-server-standalone-3.1.0.jar -Dvideo.storage=com.aimmac23.hub.videostorage.LocalFileVideoStore -Dvideo.path=D:\ org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.hub.servlet.HubVideoDownloadServlet,com.aimmac23.hub.servlet.HubVideoInfoServlet -role hub

is this correct? if it is, then in @BeforeSuite I am getting null for System.getProperty("video.path")

**Comment by aimmac23** [comment]
Hi Hemanth,

It looks like the command line invocation is correct - but I was assuming you were extending the Selenium Hub, rather than trying to use that property in your tests.

The Java System Property is only available on the JVM you have set it on (its not very well named). In this case you will have at least 3 JVMs - one for the Selenium Node, one for the Selenium Hub, and another for your Selenium tests. The "video.path" property is only available on the Hub JVM, unless you set in on your Selenium test JVM as well (which I don't really recommend).

It may be simpler to explain what you're trying to accomplish - there should be a simpler solution.

Thanks,

Alasdair
