### ISSUE TITLE
VM windows: Output Black screen recorded

### ISSUE THREAD

**Issue by Niteshsuresh** [aimmac23/selenium-video-node#49]
While both hub and node are on same vm instance, the video output is coming blank. Is this something to do with vm configuration? I'm using Oracle VM box.

**Comment by aimmac23** [comment]
Hi Niteshsuresh,

Are your VMs running Windows? If so running the node either in a service or a disconnected RDP session isn't supported - its a technical decision by Microsoft not to render anything in this case (See also #37 and #18 ).

If you're running under a normal desktop session, then more information would be useful - Java version, Operating system version, etc.

Thanks,

Alasdair

**Comment by Niteshsuresh** [comment]
Thank you Alasdair for clarifying the problem. It's was indeed working fine on normal windows desktop. The moment I moved it to windows vm running on windows host, the problem appeared. 

As per ur reference in the links, Will try switching vms to Linux and acknowledge the resolution.

Thank you
Nitesh Suresh

**Comment by Niteshsuresh** [comment]
Hi Alasdair,

Have moved the grid to ubuntu desktop 16.0 and i'm getting [Issue #23].
After downgrading from 2.4 version to 1.10 as per the resolution method in #23  https://aimmac23.com/public/misc/selenium-video-node-1.10-SNAPSHOT-issue23.jar

The things are working fine!

Please suggest.

Thank you.
Nitesh Suresh

**Comment by aimmac23** [comment]
Hi Nitresh,

That doesn't make a lot of sense to me - the issue #23  was due to the JNA path overrides not working correctly when the binaries had a version suffix (and the later version of VPX were not binary-compatible).

Would you mind running with "-Djna.debug_load=true" and pasting the output somewhere?

Thanks,

Alasdair

**Comment by Niteshsuresh** [comment]
Hi Alasdair,

Thank you for the reply.

Kindly find the link below
https://gist.github.com/Niteshsuresh/38d53f831907a81c9d2d96afe713ce75

Thank you
Nitesh

**Comment by aimmac23** [comment]
It does seem to be using the system libvpx dependency:

a130c000-a14fc000 r-xp 00000000 08:01 9222       /usr/lib/i386-linux-gnu/libvpx.so.3.0.0
a14fc000-a14fd000 r--p 001ef000 08:01 9222       /usr/lib/i386-linux-gnu/libvpx.so.3.0.0
a14fd000-a14fe000 rw-p 001f0000 08:01 9222 /usr/lib/i386-linux-gnu/libvpx.so.3.0.0

I think I've just figured out why its doing that - the long and short of it is that the system dependency got loaded when we first tried to load 64-bit binaries (by adding the 64-bit binaries to the highest priority search path, but at that point the system 32-bit binaries were on the path as well).

The fix for this one should really check for 32bit/64bit first, instead of relying on loading failures (com.sun.jna.Platform.is64bit() ?)
